# type: ignore
"""Type stubs para pyautogui."""

from typing import Any, List

def getWindowsWithTitle(title: str) -> List[Any]: ...
def hotkey(*args: str) -> None: ...
def write(text: str, interval: float = 0.0) -> None: ...
def press(key: str) -> None: ...
